source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TotalObserver_Example', :exclusive => true do
  pod "TotalObserver/Shorthand", :path => "../"
  pod 'libextobjc/EXTKeyPathCoding'
end

target 'TotalObserver_Tests', :exclusive => true do
  pod "TotalObserver/Shorthand", :path => "../"
end

